name: Core
description: Core for my senior project
api-version: '1.20'
version: 1.0-SNAPSHOT
main: me.leaf.devs.Main
author: Leaf
load: POSTWORLD
depends: [NBTAPI, Sentinel, Citizens]
commands:
  god:
    description: Enter god mode.
    usage: /<command>
  item:
    description: Gives you an item
    usage: /<command> <item>
  mob:
    description: Spawns a mob
    usage: /<command> <mob>
  nbt:
    description: View NBT of an item
    usage: /<command>
  stats:
    description: View ur stats
    usage: /<command>
  playsong:
    description: Play a song from the nbs files
    usage: /<command> <song>
  class:
    description: Pick your class
    usage: /<command> <class>
  fixstats:
    description: Fix your stats if they are not displayed correctly
    usage: /<command>
